# Generated by Django 4.2.6 on 2024-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
